data:
    type: "LLdataset"
    train_dataset: "MAI_dataset"
    val_dataset: "MAI_dataset"
    patch_size: 256
    channels: 3
    num_workers: 4
    data_dir: "/data/ISP/AAAI-25/MAI_dataset"
    ckpt_dir: "ckpt/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    num_sampling_timesteps: 25

training:
    batch_size: 16
    n_epochs: 200
    validation_freq: 2000

sampling:
    batch_size: 1
    img_save_path: '/data/ISP/AAAI-25/ISPDiffuser_final_code/results_MAI/'

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001